# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ONigiry' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'Alamofire'
pod 'SnapKit', '~> 5.6.0'

  # Pods for ONigiry

  target 'ONigiryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ONigiryUITests' do
    # Pods for testing
  end



end